# Generated by Django 4.2.13 on 2026-03-08 11:51

import business_forms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20, verbose_name='Я увидел(а) эту анкету в:')),
                ('bought_products', models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], max_length=20, verbose_name='Вы покупали какие-то мои продукты?')),
                ('city', models.CharField(max_length=120, verbose_name='Город проживания в настоящий момент')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация (рефракционный хирург, ординатор, аспирант, врач-диагност и т.д.)')),
                ('income_rub', models.CharField(max_length=120, verbose_name='Ваш средний доход в месяц, в рублях, суммарный со всех источников')),
                ('operations_status', models.CharField(choices=[('self', 'Делаю самостоятельно'), ('mentor', 'Делаю под контролем наставника'), ('plan_to_start', 'Не делаю, планирую начать'), ('not_planning', 'Не делаю, не планирую начинать'), ('expand_horizon', 'Хочу изучить для расширения кругозора')], max_length=40, verbose_name='Рефракционные операции (лазерные коррекции):')),
                ('study_goal', models.TextField(verbose_name='Зачем вы хотите изучить базовый курс рефракционной хирургии?')),
                ('current_difficulties', models.TextField(verbose_name='Какие сложности есть сейчас в области рефракционной хирургии? Что останавливает от того, чтобы достичь целей выше?')),
                ('attempted_solutions', models.TextField(verbose_name='Что уже пробовали делать, чтобы решить проблему? Что помогло, а что - не очень?')),
                ('subscription_info', models.TextField(verbose_name='Как давно вы на меня подписаны и откуда узнали?')),
                ('top_questions', models.TextField(verbose_name='ТОП-1 или ТОП-3 вопроса по рефракционной хирургии, которые вы хотите решить прямо сейчас:')),
                ('warmup_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='На сколько от 0 до 10 вы прогреты, чтобы начать у меня обучение любого формата?')),
                ('workload_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Оцените уровень вашей занятости от 0 до 10')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ваше ФИО')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на ваш инстаграм')),
                ('telegram_channel', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на ваш телеграм-канал')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на ваш личный телеграм (не канал) в формате https://t.me/doc_malahova или через @')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Согласен с политикой обработки персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Анкета предзаписи на базовый курс по рефракционной хирургии',
                'verbose_name_plural': 'Анкеты предзаписи на базовый курс по рефракционной хирургии',
            },
        ),
        migrations.CreateModel(
            name='BusinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_photo_path)),
                ('spasibo_photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_spasibo_path)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Конфигурации форм',
                'verbose_name_plural': 'Конфигурации форм',
            },
        ),
    ]
